package.path='./src/?.lua;'..package.path
local uv=require('luv')
local store=require('store')
local dir=assert(uv.fs_mkdtemp((os.getenv('TMPDIR') or '/tmp')..'/profile history.XXXXXX'))
local function record(id) return {schema='performance-history/v1',kind='observation',project='first_project',id=id,datetime_utc='2026-10-02T12:00:00.001Z',eligible=false} end
local s=store.open('file://'..dir,'first_project')
assert(s:write(record('run1'))=='created')
assert(s:write(record('run1'))=='exists')
local r=record('run1'); r.eligible=true
assert(not pcall(function() s:write(r) end),'conflicting identity must not overwrite')
local files=assert(uv.fs_scandir(dir))
assert(uv.fs_scandir_next(files)=='first_project--observation--run1.ndjson','project name missing from filename')
local other=store.open('file://'..dir,'second_project')
local second=record('run1'); second.project='second_project'; other:write(second)
assert(#s:read()==1 and #other:read()==1,'project namespaces mixed')
local file=assert(io.open(dir..'/first_project--observation--broken.ndjson','w')); file:write('{bad\n'); file:close()
assert(not pcall(function() s:read() end),'malformed history silently ignored')
assert(uv.fs_unlink(dir..'/first_project--observation--broken.ndjson'))
local outsider=dir..'/outsider'; file=assert(io.open(outsider,'w')); file:write('unmodified'); file:close()
assert(uv.fs_symlink(outsider,dir..'/first_project--observation--link.ndjson'))
assert(not pcall(function() s:write(record('link')) end),'symlink was followed')
assert(not pcall(function() store.open('https://example.com','p') end))
assert(not pcall(function() store.open('file://relative','p') end))
assert(not pcall(function() store.open('file://'..dir,'../escape') end))
local good=store.open('file://'..dir,'safe')
local ok=record('unique'); ok.project='safe'; good:write(ok)
assert(#good:read()==1)
assert(not pcall(function() store.open('file://'..dir,'first_project--observation') end),'ambiguous filename namespace accepted')
local pending=assert(io.open(dir..'/.pending-interrupted','wb')); pending:write('{partial'); pending:close()
assert(#good:read()==1,'interrupted temp file entered history')
assert(uv.fs_chmod(dir,tonumber('500',8)))
local denied=record('denied'); denied.project='safe'
assert(not pcall(function() good:write(denied) end),'read-only directory admitted a write')
assert(uv.fs_chmod(dir,tonumber('700',8)))
print('PASS: atomic history, namespace, idempotency and corruption adapters')
